### ISSUE TITLE
"Save as..." Feature

### ISSUE THREAD

**Issue by HernanSzel** [vitomirs/JRPrintPreview#1]
Hey this is what i needed, it's great. Do you plan to add a "save as..." feature in the near future?

Anyway thanks!

**Comment by DigitalVS** [comment]
Print preview window is intended to preview the report look and eventually to print it. Options like "Save as..." and "Print" (without previewing) are more suited to be triggered outside of this class, e.g. from menu option or toolbar button on the same level from which this window is opened. Thus, currently I do not have a plan to add a "Save as..." feature.

But, for those who want to have "Save as..." feature as part of the print preview window, it is easy to add a new button to the toolbar, then to open a `FileChooser` dialog and finally to export report with their own code.

**Comment by georgemoralis** [comment]
is it possible to ovveride the saving options jasper ? I don't want to write my own pdf exporter if i can use the jasper's one

**Comment by DigitalVS** [comment]
I didn't try it but I don't see why it wouldn't be possible to use save contributors from `net.sf.jasperreports.view` package, like in `JRViewer` class. However, programmer has to set any specific export parameters he needs, and anyway it probably wouldn't be less code then to write his own code.

Here is the code I use for data export. If you need only export to the PDF, it can be even significantly shorter.

``` java
  public void export(String fileChooserTitle, String defaultFileName, 
    Map<String, Object> paramMap, JRBeanCollectionDataSource dataSource) {
    FileChooser fileChooser = new FileChooser();
    fileChooser.setTitle(fileChooserTitle);
    fileChooser.setInitialFileName(defaultFileName);
    fileChooser.setInitialDirectory(new File(AppSettings.exportPath));
    fileChooser.getExtensionFilters().addAll(
        new FileChooser.ExtensionFilter("PDF files", "*.pdf"),
        new FileChooser.ExtensionFilter("Excel files", "*.xlsx"),
        new FileChooser.ExtensionFilter("Word files", "*.docx"));
    File selectedFile = fileChooser.showSaveDialog(ownerWindow.getScene().getWindow());

    if (selectedFile != null) {
      ownerWindow.getScene().setCursor(Cursor.WAIT);

      if (!paramMap.containsKey(JRParameter.REPORT_LOCALE))
        paramMap.put(JRParameter.REPORT_LOCALE, Locale.getDefault());

      try {
        Exporter exporter;

        switch (Utils.getFileExtension(selectedFile).toLowerCase()) {
          case "pdf":
            exporter = new JRPdfExporter();
            SimplePdfExporterConfiguration config = new SimplePdfExporterConfiguration();
            config.setMetadataCreator(AppSettings.APP_NAME + " " + AppSettings.APP_VERSION);
            exporter.setConfiguration(config);
            break;
          case "xlsx":
            exporter = new JRXlsxExporter();
            break;
          case "docx":
            exporter = new JRDocxExporter();
            break;
          default:
            return;
        }

        exporter.setExporterInput(new SimpleExporterInput(
          JasperFillManager.fillReport(jasperReport, paramMap, dataSource)));
        exporter.setExporterOutput(new SimpleOutputStreamExporterOutput(selectedFile));
        exporter.exportReport();
      } catch (JRException ex) {
        ex.printStackTrace();
        Logger.getLogger(getClass().getName()).severe(ex.getMessage());
      }

      ownerWindow.getScene().setCursor(Cursor.DEFAULT);
    }
  }
```

`Utils.getFileExtension()` is a simple utility method to return part of the string after the last '.' character.
