### ISSUE TITLE
How to change preview icons?

### ISSUE THREAD

**Issue by paulocoutinhox** [vitomirs/JRPrintPreview#3]
Hi,

How to change preview icons?

![image](https://user-images.githubusercontent.com/395096/62733567-4828ab00-b9fd-11e9-9bf4-2383fab46e33.png)

Thanks for the maven integration. It solve all problems.

**Comment by DigitalVS** [comment]
Currently, icons are reused from JasperReports.  Whole toolbar is initialized in JRPrintPreview.java initComponents() method. If you want different icons, or tooltips, or want to remove some buttons, or whatever else, your should change this method. 
This whole project is basically one fairly short file, and to make any customization you'll have to change that source code. Sorry, there is no interface to do it from the outside.
